export { add } from "./src/main/ets/utils/Calc"
export { HWEmptyPage } from  "./src/main/ets/pages/HWEmptyPage"
export { HWSuccessPage } from "./src/main/ets/pages/HWSuccessPage"

export { ShareTipInfo, createShareInfo } from  "./src/main/ets/utils/ShareTipInfo"
export { ShareTipView } from "./src/main/ets/utils/ShareTipView"

export { ShareResManager } from './src/main/ets/utils/ShareResManager';

//应该是下面这种 export default
// import ShareTipInfoTT from './src/main/ets/utils/ShareTipInfoTT'
