/**
 * Constants for breakpoint.
 */
export class BreakpointConstants {
  /**
   * Breakpoints that represent small device types.
   */
  static readonly BREAKPOINT_SM: string = 'sm';

  /**
   * Breakpoints that represent middle device types.
   */
  static readonly BREAKPOINT_MD: string = 'md';

  /**
   * Breakpoints that represent large device types.
   */
  static readonly BREAKPOINT_LG: string = 'lg';

  /**
   * Grid row column list.
   */
  static readonly GRID_ROW_COLUMNS: number[] = [4, 8, 12, 15, 11, 3, 6];

  /**
   * Grid column span list.
   */
  static readonly GRID_COLUMN_SPANS: number[] = [2, 3, 4, 8, 12, 5, 7];
}