export default class SetItemModel {

  public title: String = '';

  public image: Resource | null = null;

  public  isArrow:Boolean = false;

  public  items:String[] = [];

  public  cid:String = '';

  public  desc:String = '';
  // constructor(title: String, image: String, arrow:Boolean,cid:String) {
  //   this.title = title
  //   this.image = image
  //   this.isArrow = arrow
  //   this.cid = cid
  // }
}



