
export let TEST_WIDTH:number = 350
export let TEST_HEIGHT:number = 750

export class HWConstants {

  /**
   * Full width.
   */
  static readonly FULL_WIDTH: string = '100%';

  /**
   * Full height.
   */
  static readonly FULL_HEIGHT: string = '100%';

  /**
   * Larger font weight.
   */
  static readonly FONT_WEIGHT_LARGE: number = 700;
  static readonly FONT_OPACITY: number = 0.6;
  static readonly FONT_SIZE_LARGE: number = 24;
  static readonly FONT_SIZE_MID: number = 18;
  static readonly FONT_SIZE_SMALL: number = 14;
  static readonly COLOR_PAGE_BGC: string = '#F1F3F5';
  static readonly COLOR_BTN_BGC: string = '#0D182431';
  static readonly COLOR_FONT: string = '#182431';
  static readonly COLOR_BLUE: string = '#007DFF';
  static readonly RADIUS: number = 12;
  static readonly MARGIN: number = 12;
  static readonly PADDING: number = 16;
  static readonly HEIGHT_TARGET: number = 50;
  static readonly HEIGHT_SUB_TARGET: number = 30;
  static readonly PIC_SIZE: number = 96;
  static readonly PROGRESS_SIZE: number = 48;

  /**
   * list space.
   */
  static readonly LIST_SPACE: number = 12;
  /**
   * Current month plus one.
   */
  static readonly PLUS_ONE: number = 1;

  /**
   * The fraction or number of seconds is less than 10.
   */
  static readonly TEN: number = 10;
}

